/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './ngc-pagination.module';
import * as i2 from '@angular/common';
export const NgcPaginationModuleNgFactory:i0.NgModuleFactory<i1.NgcPaginationModule> = i0.ɵcmf(i1.NgcPaginationModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.NgLocalization,i2.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(512,i2.CommonModule,
          i2.CommonModule,([] as any[])),i0.ɵmpd(512,i1.NgcPaginationModule,i1.NgcPaginationModule,
          ([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2d1c3Rhdm9jb3N0YXcvU2l0ZXMvSFRNTC9QUk9KRUNUUy9uZ2MtcGFnaW5hdGlvbi9tb2R1bGUvbmdjLXBhZ2luYXRpb24ubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2d1c3Rhdm9jb3N0YXcvU2l0ZXMvSFRNTC9QUk9KRUNUUy9uZ2MtcGFnaW5hdGlvbi9tb2R1bGUvbmdjLXBhZ2luYXRpb24ubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
