/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './ngc-pagination.component';
const styles_NgcPaginationComponent:any[] = ['#exibition[_ngcontent-%COMP%] {\n    display: flex;\n  }\n\n  [_nghost-%COMP%]     .page.active {\n    background: #4285F4;\n    color:white;\n    box-shadow: 0 2px 5px 0 rgba(0,0,0,.16), 0 2px 10px 0 rgba(0,0,0,.12);\n  }\n\n  [_nghost-%COMP%]     button {\n    min-width: 33px;\n    min-height: 33px;\n    padding: 0px;\n    background: none;\n  }\n\n  [_nghost-%COMP%]     .page {\n    color: #0275d8;\n    background-color: #fff;\n    cursor: pointer;\n    color:black;\n    width:33px;\n    height: 100%;\n    border-radius: 2px;\n    padding: 0px;\n  }'];
export const RenderType_NgcPaginationComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:0,
    styles:styles_NgcPaginationComponent,data:{}});
export function View_NgcPaginationComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(2,[(_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,(null as any),
      (null as any),3,'div',[['id','exibition']],(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['\n      '])),i0.ɵncd((null as any),
      0),(_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵted((null as any),
      ['\n  ']))],(null as any),(null as any));
}
export function View_NgcPaginationComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'ngc-pagination',
      ([] as any[]),(null as any),(null as any),(null as any),View_NgcPaginationComponent_0,
      RenderType_NgcPaginationComponent)),i0.ɵdid(114688,(null as any),0,i1.NgcPaginationComponent,
      [i0.ChangeDetectorRef],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const NgcPaginationComponentNgFactory:i0.ComponentFactory<i1.NgcPaginationComponent> = i0.ɵccf('ngc-pagination',
    i1.NgcPaginationComponent,View_NgcPaginationComponent_Host_0,{config:'config'},
    {paginationEvents:'paginationEvents'},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2d1c3Rhdm9jb3N0YXcvU2l0ZXMvSFRNTC9QUk9KRUNUUy9uZ2MtcGFnaW5hdGlvbi9tb2R1bGUvbmdjLXBhZ2luYXRpb24uY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2d1c3Rhdm9jb3N0YXcvU2l0ZXMvSFRNTC9QUk9KRUNUUy9uZ2MtcGFnaW5hdGlvbi9tb2R1bGUvbmdjLXBhZ2luYXRpb24uY29tcG9uZW50LnRzIiwibmc6Ly8vVXNlcnMvZ3VzdGF2b2Nvc3Rhdy9TaXRlcy9IVE1ML1BST0pFQ1RTL25nYy1wYWdpbmF0aW9uL21vZHVsZS9uZ2MtcGFnaW5hdGlvbi5jb21wb25lbnQudHMuTmdjUGFnaW5hdGlvbkNvbXBvbmVudC5odG1sIiwibmc6Ly8vVXNlcnMvZ3VzdGF2b2Nvc3Rhdy9TaXRlcy9IVE1ML1BST0pFQ1RTL25nYy1wYWdpbmF0aW9uL21vZHVsZS9uZ2MtcGFnaW5hdGlvbi5jb21wb25lbnQudHMuTmdjUGFnaW5hdGlvbkNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgIDxkaXYgaWQ9XCJleGliaXRpb25cIj5cbiAgICAgIDxuZy1jb250ZW50PjwvbmctY29udGVudD5cbiAgICA8L2Rpdj5cbiAgIiwiPG5nYy1wYWdpbmF0aW9uPjwvbmdjLXBhZ2luYXRpb24+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7b0JDQUEsMkNBQ0k7TUFBQTtNQUFBLDhCQUFvQixvREFDbEI7TUFBQSxHQUF5QiwyQ0FDckI7TUFBQTs7O29CQ0hWO01BQUE7dUNBQUEsVUFBQTtNQUFBO0lBQUE7Ozs7OyJ9
